INSERT INTO CLIENTE (BUSINESS_AREA, CNPJ, NAME) VALUES ('Development', '71661132', 'Julian');
INSERT INTO CLIENTE (BUSINESS_AREA, CNPJ, NAME) VALUES ('Mantencao', '45454545', 'Armando');
INSERT INTO CLIENTE (BUSINESS_AREA, CNPJ, NAME) VALUES ('Design', '8685868', 'Pepe');

INSERT INTO VENDEDOR (CPF, NAME, SALARY) VALUES ('74343434', 'Jhones', '665.0');
INSERT INTO VENDEDOR (CPF, NAME, SALARY) VALUES ('78686668', 'Francini', '343');
INSERT INTO VENDEDOR (CPF, NAME, SALARY) VALUES ('56565665', 'Filipe', '1009');

INSERT INTO VENDA (VENDEDOR_ID_ID) VALUES ('1');
INSERT INTO VENDA (VENDEDOR_ID_ID) VALUES ('2');
INSERT INTO VENDA (VENDEDOR_ID_ID) VALUES ('3');

INSERT INTO ITEM (ITEM_CODE, PRICE, QTD, VENDA_ID) VALUES ('555', '18.5', '2', '1');
INSERT INTO ITEM (ITEM_CODE, PRICE, QTD, VENDA_ID) VALUES ('666', '20.7', '1', '2');
INSERT INTO ITEM (ITEM_CODE, PRICE, QTD, VENDA_ID) VALUES ('777', '70.0', '5', '3');